server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://db-illk5-kr.vpc-pub-cdb.ntruss.com:3306/catpus
    username: root
    password: pms41414
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 7200
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true