spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/catpus?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: pms41414
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 버전에 따라 방언 설정
    hibernate:
      ddl-auto: update

  session:
    store-type: none


logging:
  level:
    root: INFO
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M

server:
  address: http://101.101.216.159/