server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-illk5-kr.vpc-pub-cdb.ntruss.com:3306/catpus
    username: user
    password: user1234!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true